// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmkghoC1I5e3u9ATMZ9sKKhYJmJAcBQM0',
    appId: '1:754645167063:web:52b66dfe8e376fe3e4f992',
    messagingSenderId: '754645167063',
    projectId: 'finder-dad5f',
    authDomain: 'finder-dad5f.firebaseapp.com',
    storageBucket: 'finder-dad5f.firebasestorage.app',
    measurementId: 'G-C9Z4D6XL2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7gz7pWMXKUT4UMEGba1W9nJKFmeOV98',
    appId: '1:754645167063:android:f9b2b169ae79b797e4f992',
    messagingSenderId: '754645167063',
    projectId: 'finder-dad5f',
    storageBucket: 'finder-dad5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLPiI26DdiNTZac0dS3LX5iWKwUOvux4',
    appId: '1:754645167063:ios:24fc4092c22cf280e4f992',
    messagingSenderId: '754645167063',
    projectId: 'finder-dad5f',
    storageBucket: 'finder-dad5f.firebasestorage.app',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLPiI26DdiNTZac0dS3LX5iWKwUOvux4',
    appId: '1:754645167063:ios:24fc4092c22cf280e4f992',
    messagingSenderId: '754645167063',
    projectId: 'finder-dad5f',
    storageBucket: 'finder-dad5f.firebasestorage.app',
    iosBundleId: 'com.example.finder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmkghoC1I5e3u9ATMZ9sKKhYJmJAcBQM0',
    appId: '1:754645167063:web:a654411e1e8395a1e4f992',
    messagingSenderId: '754645167063',
    projectId: 'finder-dad5f',
    authDomain: 'finder-dad5f.firebaseapp.com',
    storageBucket: 'finder-dad5f.firebasestorage.app',
    measurementId: 'G-BEX87PCF9Q',
  );
}
